### ISSUE TITLE
navigation and posts are not showing

### ISSUE THREAD

**Issue by flackojrdn** [kailoon/kailoon-next#1]
after setting up the sanity it does not show a navigation bar, current stack and latest projects bar as also posts.

**Comment by kailoon** [comment]
Did you set the permission correctly on sanity?

**Comment by flackojrdn** [comment]
How did you setup this code with sanity? Maybe I am doing something wrong.

**Comment by flackojrdn** [comment]
building give this error:
```
> Build error occurred
TypeError: Cannot read properties of null (reading 'current')
    at C:\Users\theed\kailoon-next-main\cgl-fe\.next\server\pages\writings\[slug].js:128:33
    at Array.map (<anonymous>)
    at getStaticPaths (C:\Users\theed\kailoon-next-main\cgl-fe\.next\server\pages\writings\[slug].js:126:25)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async buildStaticPaths (C:\Users\theed\kailoon-next-main\cgl-fe\node_modules\next\dist\build\utils.js:497:31)
    at async C:\Users\theed\kailoon-next-main\cgl-fe\node_modules\next\dist\build\utils.js:640:119
    at async Span.traceAsyncFn (C:\Users\theed\kailoon-next-main\cgl-fe\node_modules\next\dist\trace\trace.js:75:20) {
  type: 'TypeError'
 }
```
